name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run all

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2
    - shell: bash
      run: |
        npm install
        npm run all
    - uses: ./
    - name: init powershell
      run: conda init --system powershell
    - name: Run conda list
      run: conda list
    - name: Install stuff
      run: |
        $ErrorActionPreference = 'stop';
        conda env list
        get-command mamba
        mamba --version
        write-host 'AAAAA'
        $proc = Start-Process mamba -ArgumentList 'install','-y','-c conda-forge','xtensor' -NoNewWindow -Wait -PassThru;
        write-host "EXITCODE: ${proc.ExitCode}"
        write-host $proc.StandardOutput
        write-host $proc.StandardError
        write-host 'BBBBB'
        conda list
        write-host 'CCCCC'
        mamba install --yes conda=4.8.2
        write-host 'DDDDD'
    - name: Install Notebook and widgets
      run: |
        mamba install -y -c conda-forge xtensor
        mamba install -y -c conda-forge notebook ipywidgets
    - name: List the packages
      run: mamba list
