name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

defaults:
  run:
    shell: powershell

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      run: |
        npm install
        npm run all

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run all
    - uses: ./
    - name: init powershell
      run: conda init --system powershell
    - name: Run conda list
      run: conda list
    - name: Install stuff
      run: mamba install -y -c conda-forge xtensor
    - name: Install Notebook and widgets
      run: mamba install -y -c conda-forge notebook ipywidgets
    - name: List the packages
      run: mamba list
